"""
Compliance Agent
=================
Adds GDPR and responsible AI notes.
"""

import logging
from typing import Any, Dict
from app.config import settings
from app.services.llm_service import generate_text

logger = logging.getLogger(__name__)


class ComplianceAgent:
    """Adds GDPR and responsible AI notes using LLMs."""
    
    async def execute(self, context: Dict[str, Any]) -> str:
        """Generate compliance and ethics notes via LLM."""
        logger.info("▶ ComplianceAgent: Generating GDPR and responsible AI notes via LLM")
        
        region = context["region"]
        sector = context["sector"]
        description = context["project_description"]
        
        if settings.use_llm:
            try:
                system_instruction = (
                    "You are a Senior Legal and Ethical Compliance Officer at MzN International. "
                    "Your advice is analytical, nuanced, and focuses on actionable risk mitigation "
                    "regarding GDPR and ethical representation in the global development sector."
                )

                prompt = f"""
Perform a deep Ethical & Regulatory compliance review for:
Sector: {sector}
Region: {region}
Project: {description}

REQUIREMENTS:
1. One paragraph on GDPR specific to {region}.
2. Two bulleted ethical risks and mitigation bullets.

OUTPUT FORMAT:
Return a JSON list of 3-4 professional advice strings.
"""
                output = await generate_text(prompt, system_instruction=system_instruction)
                import json
                clean = output.strip().strip("```json").strip("```").strip()
                parsed = json.loads(clean)
                if isinstance(parsed, list):
                    return "\n\n".join(str(item) for item in parsed)
                return str(parsed)
            except Exception as e:
                logger.error(f"ComplianceAgent LLM failed: {e}")

        # Fallback to templates
        if "europe" in region.lower() or "eu" in region.lower():
            gdpr_note = "Strict GDPR provisions apply in this region. All data collection and M&E activities require explicit consent mechanisms."
        else:
            gdpr_note = "GDPR-equivalent regional data protection laws must be adhered to. Do not store PII in unstructured formats."

        return f"""
ROUTINE COMPLIANCE REVIEW:
--------------------------
The proposed strategy has been reviewed by the ComplianceAgent.

1. Data Protection & Privacy:
   - {gdpr_note}
   - AI Processing Warning: Outputs generated by this system must remain internal until reviewed by human staff. Do not expose confidential client project descriptions directly to external unvetted LLMs.

2. Responsible AI & Hallucination Mitigation:
   - Funding matches reflect institutional database entries only. Deadlines and eligibility MUST be manually verified on donor portals.
   - Proposal drafting utilized internal MzN project context. Synthesised intervention strategies must be validated against current macro-economic realities.

3. Ethical Representation:
   - Target community representation must follow non-extractive research methodologies. Include "Do No Harm" reviews during the inception phase.

STATUS: CLEARED FOR INTERNAL DRAFTING.
""".strip()
